# uosc
osd-bar=no
border=no

# Rendering
profile=high-quality
vo=gpu-next
hwdec=auto

# Conservative debanding
deband=yes
deband-iterations=2
deband-threshold=32
deband-range=16
deband-grain=4

# Playback
autocreate-playlist=same
save-position-on-quit=yes

# Subtitles and languages
sub-auto=fuzzy
alang=jpn,jp,ja,eng,en
slang=eng,en
