require('options')

-- Bootstrap lazy.nvim
local lazypath = vim.fn.stdpath('data') .. '/lazy/lazy.nvim'
if not (vim.uv or vim.loop).fs_stat(lazypath) then
    local lazyrepo = 'https://github.com/folke/lazy.nvim.git'
    local out = vim.fn.system({ 'git', 'clone', '--filter=blob:none', '--branch=stable', lazyrepo, lazypath })
    if vim.v.shell_error ~= 0 then
        vim.api.nvim_echo({
            { 'Failed to clone lazy.nvim:\n', 'ErrorMsg' },
            { out, 'WarningMsg' },
            { '\nPress any key to exit...' },
        }, true, {})
        vim.fn.getchar()
        os.exit(1)
    end
end
vim.opt.rtp:prepend(lazypath)

local ok, lazy = pcall(require, 'lazy')
if not ok then return end

local lazy_opts = {
    ui = {
        border = 'single'
    }
}

lazy.setup('plugins', lazy_opts)

require('keymaps')
require('autocmds')
require('lsp')

-- Colorscheme: noctalia (palette generated by matugen) + live reload on SIGUSR1.
-- matugen rewrites lua/noctalia/palette.lua, then `pkill -SIGUSR1 nvim` fires
-- this handler, which re-sources colors/noctalia.lua with the fresh palette.
pcall(vim.cmd.colorscheme, 'noctalia')

local theme_signal = vim.uv.new_signal()
theme_signal:start('sigusr1', vim.schedule_wrap(function()
    pcall(vim.cmd.colorscheme, 'noctalia')
end))
