bind = SUPER, Return, spawn, $TERMINAL
bind = SUPER, b, spawn, $BROWSER
bind = SUPER, e, spawn, nautilus


### NOCTALIA
bind = SUPER, p, spawn, noctalia msg panel-toggle launcher
bind = SUPER, m, spawn, noctalia msg panel-toggle control-center
bind = SUPER+SHIFT, m, spawn, noctalia msg settings-toggle
bind = SUPER, c, spawn, noctalia msg panel-toggle clipboard
bind = SUPER+SHIFT, q, spawn, noctalia msg panel-toggle session
bind = SUPER, BackSpace, spawn, noctalia msg session lock


### SCREENSHOTS
bind = SUPER, s, spawn, noctalia msg screenshot-region
bind = SUPER+SHIFT, s, spawn, noctalia msg screenshot-annotate


### MEDIA CONTROLS
bind = NONE, XF86AudioRaiseVolume, spawn, noctalia msg volume-up 1
bind = NONE, XF86AudioLowerVolume, spawn, noctalia msg volume-down 1
bind = NONE, XF86AudioMute, spawn, noctalia msg volume-mute
bind = NONE, XF86AudioMicMute, spawn, noctalia msg mic-mute
bind = NONE, XF86AudioNext, spawn, noctalia msg media next
bind = NONE, XF86AudioPrev, spawn, noctalia msg media previous
bind = NONE, XF86AudioPlay, spawn, noctalia msg media toggle
bind = NONE, XF86AudioPause, spawn, noctalia msg media toggle


### BRIGHTNESS CONTROLS
bind = NONE, XF86MonBrightnessUp, spawn, noctalia msg brightness-up 1
bind = NONE, XF86MonBrightnessDown, spawn, noctalia msg brightness-down 1
bindcl = SUPER+SHIFT, BackSpace, sleep_toggle_monitor, DP-1
bindcl = SUPER+SHIFT, BackSpace, sleep_toggle_monitor, HDMI-A-1


### WINDOW MANAGEMENT
bind = SUPER, q, killclient
bind = SUPER, v, togglefloating
bind = SUPER, f, togglefullscreen
bind = SUPER, g, toggleglobal
bind = SUPER, i, minimized
bind = SUPER+SHIFT, i, restore_minimized, 0
bind = SUPER, backslash, toggle_scratchpad


### FOCUS & MOVEMENT
bind = SUPER, Tab, focusstack, next
bind = SUPER+SHIFT, Tab, focusstack, prev

bind = SUPER, h, focusdir, left
bind = SUPER, j, focusdir, down
bind = SUPER, k, focusdir, up
bind = SUPER, l, focusdir, right

bind = SUPER+SHIFT, h, move_client, left
bind = SUPER+SHIFT, j, move_client, down
bind = SUPER+SHIFT, k, move_client, up
bind = SUPER+SHIFT, l, move_client, right

bind = SUPER+CTRL, h, resizewin, -40, 0
bind = SUPER+CTRL, j, resizewin, 0, +40
bind = SUPER+CTRL, k, resizewin, 0, -40
bind = SUPER+CTRL, l, resizewin, +40, 0


# TAGS & MONITORS
bind = SUPER, 1, view, 1, 0
bind = SUPER, 2, view, 2, 0
bind = SUPER, 3, view, 3, 0
bind = SUPER, 4, view, 4, 0
bind = SUPER, 5, view, 5, 0
bind = SUPER, 6, view, 6, 0
bind = SUPER, 7, view, 7, 0
bind = SUPER, 8, view, 8, 0
bind = SUPER, 9, view, 9, 0
bind = SUPER+SHIFT ,1, tag, 1, 0
bind = SUPER+SHIFT, 2, tag, 2, 0
bind = SUPER+SHIFT, 3, tag, 3, 0
bind = SUPER+SHIFT, 4, tag, 4, 0
bind = SUPER+SHIFT, 5, tag, 5, 0
bind = SUPER+SHIFT, 6, tag, 6, 0
bind = SUPER+SHIFT, 7, tag, 7, 0
bind = SUPER+SHIFT, 8, tag, 8, 0
bind = SUPER+SHIFT, 9, tag, 9, 0

bind = SUPER, comma, focusmon, left
bind = SUPER, period, focusmon, right
bind = SUPER+SHIFT, comma, tagmon, left
bind = SUPER+SHIFT, period, tagmon, right


### MOUSE
mousebind = SUPER, btn_left, moveresize, curmove
mousebind = SUPER, btn_right, moveresize, curresize


### LAYOUTS
bind = SUPER, n, switch_layout

bind = SUPER+SHIFT, e, set_proportion, 1.0
bind = SUPER, x, switch_proportion_preset


### SYSTEM
bind = SUPER, r, reload_config
bind = ALT, Tab, overcircle, next
bind = SUPER, o, togglejump
