allow_tearing = 2


### SYSTEM & HARDWARE
xwayland_persistence = 1
#xwayland_ignore_scale = 1
syncobj_enable = 1
allow_lock_transparent = 1


### FOCUS & INPUT
cursor_hide_timeout = 3
drag_tile_to_tile = 1
drag_tile_small = 0
drag_corner = 4


### MULTI-MONITOR & TAGS
focus_cross_monitor = 0
focusdir_only_zone_overlap = 1
exchange_cross_monitor = 0
focus_cross_tag = 1
view_current_to_back = 1
scratchpad_cross_monitor = 1
tag_gather = 1


### WINDOW BEHAVIOR
# tag_carousel = 1
