source = ./cfg/autostart.conf
source = ./cfg/visuals.conf
source-optional = ./cfg/output.conf
source = ./cfg/keybinds.conf
source = ./cfg/input.conf
source = ./cfg/layout.conf
source = ./cfg/overview.conf
source = ./cfg/rules.conf
source = ./cfg/misc.conf
source = ./cfg/env.conf

source-optional=~/.config/mango/noctalia.conf
