-- AUTO-GENERATED by noctalia/matugen — do not edit by hand.
-- Consumed by ~/.config/nvim/colors/noctalia.lua (mini.base16).
--
-- Accents are spread across the four real Material-You hues so the most
-- frequent tokens stay visually distinct (no doubling one hue into two slots):
--   strings = primary (gold) · functions = secondary (lime)
--   keywords = tertiary (green) · errors = error (red)
return {
    -- Background → foreground ramp
    base00 = '{{colors.surface_variant.default.hex}}', -- Default background
    base01 = '{{colors.surface_variant.default.hex}}', -- Lighter bg (status, line nr)
    base02 = '{{colors.surface_variant.default.hex}}', -- Selection background
    base03 = '{{colors.on_surface_variant.default.hex}}', -- Comments, invisibles
    base04 = '{{colors.on_surface_variant.default.hex}}', -- Dark foreground (status)
    base05 = '{{colors.on_surface.default.hex}}', -- Default foreground
    base06 = '{{colors.on_surface.default.hex}}', -- Light foreground
    base07 = '{{colors.on_surface.default.hex}}', -- Lightest foreground
    -- Accents
    base08 = '{{colors.error.default.hex}}', -- Variables, errors, diff-deleted (red)
    base09 = '{{colors.primary_fixed_dim.default.hex}}', -- Numbers, constants (dim gold)
    base0A = '{{colors.secondary_fixed_dim.default.hex}}', -- Types, classes, search (dim lime)
    base0B = '{{colors.primary.default.hex}}', -- Strings, diff-inserted (gold)
    base0C = '{{colors.tertiary_fixed_dim.default.hex}}', -- Escapes, regex (dim green)
    base0D = '{{colors.secondary.default.hex}}', -- Functions, methods (lime)
    base0E = '{{colors.tertiary.default.hex}}', -- Keywords, storage (green)
    base0F = '{{colors.error_container.default.hex}}', -- Deprecated, embedded tags
}
