PULSE_COOKIE=${XDG_STATE_HOME}/pulse/cookie
CUDA_CACHE_PATH=${XDG_CACHE_HOME}/nv
SSH_AUTH_SOCK=${XDG_RUNTIME_DIR}/ssh-agent.socket
CARGO_HOME=${XDG_DATA_HOME}/cargo
RUSTUP_HOME=${XDG_DATA_HOME}/rustup
GOPATH=${HOME}/.local/share/go
GOBIN=${HOME}/.local/bin
DOTNET_CLI_HOME=${XDG_DATA_HOME}/dotnet
NUGET_PACKAGES=${XDG_CACHE_HOME}/nuget
DOCKER_CONFIG=${XDG_CONFIG_HOME}/docker
